version: '3'
services:
  nsqlookupd:
    image: r.xiaozhou.net/other/nsq
    command: /nsqlookupd -broadcast-address 192.168.0.115
    network_mode: "host"
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: r.xiaozhou.net/other/nsq
    command: /nsqd --lookupd-tcp-address=192.168.0.115:4160 -broadcast-address 192.168.0.115
    network_mode: "host"
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: r.xiaozhou.net/other/nsq
    command: /nsqadmin --lookupd-http-address=192.168.0.115:4161
    network_mode: "host"
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
