---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsqadmin
    spec:
      containers:
      - name: nsqd
        image: registry.orientsoft.cn/other/nsq:latest
        command: ["/nsqadmin"]
        args: ["--lookupd-http-address=nsqlookupd:4161"]
        ports:
        - containerPort: 4171
          name: port-4171
---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
spec:
  selector:
    app: nsqadmin
  ports:
    - protocol: TCP
      port: 4171
      targetPort: 4171
      nodePort: 30171
      name: 4171-port
  type: NodePort
