---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsqlookupd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsqlookupd
    spec:
      containers:
      - name: nsqlookupd
        image: registry.orientsoft.cn/other/nsq:latest
        command: ["/nsqlookupd"]
        args: ["-broadcast-address", "192.168.0.73"]
        ports:
        - containerPort: 4160
          name: port-4160
        - containerPort: 4161
          name: port-4161
---
apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
spec:
  selector:
    app: nsqlookupd
  ports:
    - protocol: TCP
      port: 4160
      targetPort: 4160
      name: 4160-port
    - protocol: TCP
      port: 4161
      targetPort: 4161
      nodePort: 30161
      name: 4161-port
  type: NodePort
